#!/bin/bash
# get-profiles-from-buffer.sh - Alternative methods

echo "=== Method 1: Buffer Web Interface ==="
echo ""
echo "1. Go to: https://publish.buffer.com"
echo "2. Look at your connected accounts"
echo "3. Open browser DevTools (Cmd+Option+I)"
echo "4. Go to Network tab"
echo "5. Refresh the page"
echo "6. Look for GraphQL requests to api.buffer.com"
echo "7. Click 'organizations' request"
echo "8. Look for 'channels' or 'profiles' in response"
echo ""
echo "Your profile IDs will be there (long alphanumeric strings)"
echo ""
echo "=== Method 2: Browser Console ==="
echo ""
echo "In the Buffer dashboard, open console and paste:"
echo ""
echo "  copy(JSON.parse(localStorage.buffer).user.organizations[0].channels.map(c => ({id: c.id, service: c.service, username: c.username})))"
echo ""
echo "This copies profile IDs to clipboard"
echo ""
echo "=== Method 3: Inspect Element ==="
echo ""
echo "1. Right-click on your Twitter account in Buffer"
echo "2. Inspect element"
echo "3. Look for data attributes like data-profile-id"
echo ""
echo "=== Method 4: Buffer Settings Export ==="
echo ""
echo "1. Go to: https://publish.buffer.com/settings/account"
echo "2. Account Settings → Export Data"
echo "3. Look for profile IDs in exported JSON"
