#!/bin/bash
#
# OpenClaw Cron Wrapper
# Wrapper for spawning OpenClaw agents at scheduled times
# Called by crontab: 31 19 * * *
#

set -e

# Configuration
PROJECT_DIR="$HOME/.openclaw/workspace/projects/al-does-ai"
LOG_FILE="$PROJECT_DIR/logs/cron.log"
DATE=$(date +%Y-%m-%d)
DATETIME=$(date '+%Y-%m-%d %H:%M:%S %Z')
TIMESTAMP=$(date +%s)

# OpenClaw Gateway Configuration
GATEWAY_URL="http://localhost:18789"
GATEWAY_TOKEN="${OPENCLAW_TOKEN:-}"

# Change to project directory
cd "$PROJECT_DIR"

# Log function
log() {
    echo "[$DATETIME] $1" | tee -a "$LOG_FILE"
}

log "=== OpenClaw Cron Job Started ==="
log "Running at $DATETIME"

# Check if we're in cron environment
if [ -z "$TERM" ]; then
    log "Running in cron environment (no TTY)"
else
    log "Running with TTY: $TERM"
fi

# Verify project directory exists
if [ ! -d "$PROJECT_DIR" ]; then
    log "ERROR: Project directory $PROJECT_DIR does not exist"
    exit 1
fi

# Function to spawn agent via OpenClaw API
spawn_agent() {
    local agent_type="$1"
    local agent_name="$2"
    local agent_desc="$3"
    
    log "Spawning $agent_name..."
    
    # Create agent request payload
    local payload=$(cat <<EOF
{
    "action": "spawn",
    "name": "$agent_name",
    "description": "$agent_desc",
    "model": "ollama/kimi-k2.5:cloud",
    "channel": "cron",
    "workdir": "$PROJECT_DIR",
    "timeout": 1800
}
EOF
)
    
    # Try to spawn via OpenClaw API if available
    if command -v curl >/dev/null 2>&1; then
        if [ -n "$GATEWAY_TOKEN" ]; then
            response=$(curl -s -X POST "$GATEWAY_URL/api/agents/spawn" \
                -H "Content-Type: application/json" \
                -H "Authorization: Bearer $GATEWAY_TOKEN" \
                -d "$payload" 2>&1) || {
                log "Agent $agent_name spawn returned: $?"
            }
            log "Spawned $agent_name: $response"
        else
            log "No GATEWAY_TOKEN set, cannot spawn $agent_name"
        fi
    else
        log "curl not available, cannot spawn $agent_name"
    fi
}

# =============================================================================
# JOURNAL WRITER AGENT
# =============================================================================
log "--- JournalWriter Agent ---"

# Check for today's memory file
MEMORY_FILE="$PROJECT_DIR/memory/$DATE.md"
if [ -f "$MEMORY_FILE" ]; then
    log "Memory file exists: $MEMORY_FILE"
    log "Size: $(wc -c < "$MEMORY_FILE" | tr -d ' ') bytes"
else
    log "Memory file not found: $MEMORY_FILE"
    log "Creating minimal stub..."
    mkdir -p "$(dirname "$MEMORY_FILE")"
    echo "# $DATE — Daily Log" > "$MEMORY_FILE"
    echo "" >> "$MEMORY_FILE"
    echo "_Journal entry generated by cron at $DATETIME_" >> "$MEMORY_FILE"
fi

# Run JournalWriter
case "${JOURNAL_MODE:-direct}" in
    direct)
        # Direct script execution (default)
        log "Running JournalWriter in direct mode..."
        if [ -x "$PROJECT_DIR/scripts/run-journal-writer.sh" ]; then
            "$PROJECT_DIR/scripts/run-journal-writer.sh" 2>&1 | tee -a "$LOG_FILE" &
            JOURNAL_PID=$!
            log "JournalWriter started with PID $JOURNAL_PID"
        else
            # Fallback: run daily-journal.sh (synchronous)
            log "Running daily-journal.sh as fallback..."
            "$PROJECT_DIR/scripts/daily-journal.sh" 2>&1 | tee -a "$LOG_FILE"
        fi
        ;;
    agent)
        # Spawn via agent framework
        spawn_agent "journal" "JournalWriter" "Generate daily journal from memory files"
        ;;
esac

# =============================================================================
# GUIDE BUILDER AGENT
# =============================================================================
log "--- GuideBuilder Agent ---"

# Run GuideBuilder
case "${GUIDE_MODE:-direct}" in
    direct)
        log "Running GuideBuilder in direct mode..."
        if [ -x "$PROJECT_DIR/scripts/run-guide-builder.sh" ]; then
            "$PROJECT_DIR/scripts/run-guide-builder.sh" 2>&1 | tee -a "$LOG_FILE" &
            GUIDE_PID=$!
            log "GuideBuilder started with PID $GUIDE_PID"
        else
            # Fallback: run update-guide.sh (synchronous)
            log "Running update-guide.sh as fallback..."
            "$PROJECT_DIR/scripts/update-guide.sh" 2>&1 | tee -a "$LOG_FILE"
        fi
        ;;
    agent)
        spawn_agent "guide" "GuideBuilder" "Rebuild guide pages from docs"
        ;;
esac

# Wait for background processes if any
if [ -n "${JOURNAL_PID:-}" ] || [ -n "${GUIDE_PID:-}" ]; then
    log "Waiting for background processes..."
    wait ${JOURNAL_PID:-} ${GUIDE_PID:-} 2>/dev/null || true
    log "Background processes complete"
fi

# Git commit any generated files
log "--- Git Commit ---"
if [ -d ".git" ]; then
    git add -A
    if git diff --cached --quiet; then
        log "No changes to commit"
    else
        git commit -m "Cron update: $DATE [Journal + Guide]" 2>&1 | tee -a "$LOG_FILE"
        log "Git commit successful"
    fi
else
    log "Warning: Not a git repository"
fi

log "=== OpenClaw Cron Job Complete ==="
echo ""

# Report completion via notification if available
if command -v osascript >/dev/null 2>&1; then
    osascript -e "display notification \"Journal and Guide updated for $DATE\" with title \"Al Does AI\"" 2>/dev/null || true
fi

exit 0